image: registry.gitlab.com/strang3quark/simple_cv/pipeline:latest

stages:
  - build
  - deploy

build_docker_image:
  stage: build
  image: docker:20.10
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $PIPELINE_TOKEN registry.gitlab.com/simple_cv
    - cd ./deploy/scripts
  script:
    - ./docker-build.sh
  only:
    - master

deploy-brunojesuspt:
  stage: deploy
  dependencies:
    - build_docker_image
  before_script:
    - cat $KUBECONFIG_FILE >> /opt/kubeconfig.yaml
    - export KUBECONFIG=/opt/kubeconfig.yaml
    - export NAMESPACE=brunojesuspt
    - export HOST=brunojesus.pt
    - export PROTOCOL=https
    - cd ./deploy/scripts
  script:
    - ./deploy.sh
